---
language: generic

before_script:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install python3.7 python3.7-dev
  - sudo pip install tox

jobs:
  include:
    - stage: run tox
      script: tox
