---
language: generic

before_script:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install python3.8 python3.8-dev
  - sudo pip install tox

jobs:
  include:
    - stage: run tox
      script: tox
