---
language: generic

before_script:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install python3.8 python3.8-dev python3.8-distutils
  - sudo pip install tox ansible
  - ansible-galaxy collection install -r requirements.yml
  - ansible-galaxy install git+file://$(pwd) -f
  - mv ~/.ansible/roles/ansible-role-xtesting/ ~/.ansible/roles/collivier.xtesting

jobs:
  include:
    - stage: run tox
      script: tox
    - stage: run docker playbooks
      script: ansible-playbook tests/all.yml
    - script: ansible-playbook tests/proxy.yml
    - script: ansible-playbook tests/twice.yml
    - script: ansible-playbook tests/branch.yml
    - script: ansible-playbook tests/jjb.yml
    - script: ansible-playbook tests/gitlab.insert.yml
    - script: ansible-playbook tests/kind.yml
    - script: ansible-playbook tests/chainedci.yml
    - stage: run kubernetes playbooks
      script: ansible-playbook tests/kubernetes.yml
    - script: ansible-playbook tests/proxy_kubernetes.yml
    - stage: deploy your own CI/CD toolchain from scratch
      script: >
        cd tests/hello &&
        sudo docker build -t 127.0.0.1:5000/hello . &&
        ansible-playbook site.yml &&
        sudo docker push 127.0.0.1:5000/hello
    - stage: write your own Xtesting driver
      script: >
        cd tests/weather &&
        sudo docker build -t 127.0.0.1:5000/weather . &&
        ansible-playbook site.yml &&
        sudo docker push 127.0.0.1:5000/weather
