---
- name: Installing libapt-pkg-dev
  become: true
  shell:
    cmd: apt-get install libapt-pkg-dev -y
    warn: false  # the apt module depends on libapt-pkg-dev
  changed_when: true
- name: Installing python-apt
  become: "{{ not lookup('env','VIRTUAL_ENV') }}"
  shell: |
    pip install \
      git+https://salsa.debian.org/apt-team/python-apt.git\#egg=python-apt
  changed_when: true
- name: Installing python-pip
  become: true
  apt:
    name: python-pip
    update_cache: true
  when:
    - ansible_python.version.major==2
- name: Installing python3-pip
  become: true
  apt:
    name: python3-pip
    update_cache: true
  when:
    - ansible_python.version.major==3
- name: Installing docker.io
  become: true
  apt:
    name: docker.io
    update_cache: true
