---
- name: Installing python-apt
  become: true
  shell:
    cmd: apt-get install python-apt -y
    warn: false  # the apt module depends on python-apt
  changed_when: true
  when:
    - ansible_python.version.major==2
- name: Installing python3-apt
  become: true
  shell:
    cmd: apt-get install python3-apt -y
    warn: false  # the apt module depends on python-apt
  changed_when: true
  when:
    - ansible_python.version.major==3
- name: Installing python-pip
  become: true
  apt:
    name: python-pip
    update_cache: true
  when:
    - ansible_python.version.major==2
- name: Installing python3-pip
  become: true
  apt:
    name: python3-pip
    update_cache: true
  when:
    - ansible_python.version.major==3
- name: Gathering the package facts
  package_facts:
    manager: auto
- name: Installing docker.io
  become: true
  apt:
    name: docker.io
    update_cache: true
  when:
    - ansible_lsb.id!='Raspbian'
    - not 'docker-ce' in ansible_facts.packages
- name: Installing docker
  become: true
  shell: curl -sSL https://get.docker.com | sh
  when:
    - ansible_lsb.id=='Raspbian'
    - not 'docker-ce' in ansible_facts.packages
