---
- name: Installing python-dev
  become: true
  shell:
    cmd: apt-get update && apt-get install python-dev -y
    warn: false  # the apt module indirectly depends on python-dev
  when:
    - ansible_python.version.major==2
    - lookup('env','VIRTUAL_ENV')
- name: Installing python3-dev
  become: true
  shell:
    cmd: apt-get update && apt-get install python3-dev -y
    warn: false  # the apt module indirectly depends on python3-dev
  when:
    - ansible_python.version.major==3
    - lookup('env','VIRTUAL_ENV')
- name: Installing build-essential and libapt-pkg-dev
  become: true
  shell:
    cmd: apt-get update && apt-get install build-essential libapt-pkg-dev -y
    warn: false  # the apt module depends on libapt-pkg-dev
  when:
    - lookup('env','VIRTUAL_ENV')
- name: Installing python-apt via source
  shell: |
    pip install \
      git+https://salsa.debian.org/apt-team/python-apt.git@2.0.0\#egg=python-apt
  when:
    - lookup('env','VIRTUAL_ENV')
- name: Installing python-apt
  become: true
  shell:
    cmd: apt-get update && apt-get install python-apt -y
    warn: false  # the apt module depends on python-apt
  changed_when: true
  when:
    - ansible_python.version.major==2
    - not lookup('env','VIRTUAL_ENV')
- name: Installing python3-apt
  become: true
  shell:
    cmd: apt-get update && apt-get install python3-apt -y
    warn: false  # the apt module depends on python-apt
  changed_when: true
  when:
    - ansible_python.version.major==3
    - not lookup('env','VIRTUAL_ENV')
- name: Installing python-pip
  become: true
  apt:
    name: python-pip
    update_cache: true
  when:
    - not lookup('env','VIRTUAL_ENV')
    - ansible_python.version.major==2
- name: Installing python3-pip
  become: true
  apt:
    name: python3-pip
    update_cache: true
  when:
    - not lookup('env','VIRTUAL_ENV')
    - ansible_python.version.major==3
- name: Gathering the package facts
  package_facts:
    manager: auto
- name: Installing docker.io
  become: true
  apt:
    name: docker.io
    update_cache: true
  when:
    - ansible_lsb.id!='Raspbian'
    - not (ansible_distribution =='Debian' and
        ansible_distribution_major_version|int <= 9)
    - not 'docker-ce' in ansible_facts.packages
- name: Installing curl
  become: true
  apt:
    name: curl
    update_cache: true
  when:
    - ansible_lsb.id ==' Raspbian' or (
        ansible_distribution =='Debian' and
        ansible_distribution_major_version|int < 10)
    - not (ansible_distribution =='Debian' and
        ansible_distribution_version == 'testing')
    - not 'docker-ce' in ansible_facts.packages
- name: Installing docker
  become: true
  shell: curl -sSL https://get.docker.com | sh
  when:
    - ansible_lsb.id ==' Raspbian' or (
        ansible_distribution =='Debian' and
        ansible_distribution_major_version|int < 10)
    - not (ansible_distribution =='Debian' and
        ansible_distribution_version == 'testing')
    - not 'docker-ce' in ansible_facts.packages
