---
- name: Installing python-pip
  become: true
  apt:
    name: python-pip
    update_cache: true
  when:
    - ansible_python.version.major==2
- name: Installing python3-pip
  become: true
  apt:
    name: python3-pip
    update_cache: true
  when:
    - ansible_python.version.major==3
- name: Installing docker.io
  become: true
  apt:
    name: docker.io
    update_cache: true
