---
- name: Adding ansible_user to docker group
  become: true
  user:
    name: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    groups:
      - docker
    append: true
- name: Loading docker group into ansible_user
  command: newgrp docker
  when:
    - ansible_os_family == 'RedHat'
- name: Creating /etc/systemd/system/docker.service.d
  become: true
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'
  when:
    - "'http_proxy' in ansible_env or 'https_proxy' in ansible_env"
- name: Creating /etc/systemd/system/docker.service.d/http-proxy.conf
  become: true
  template:
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    mode: '0644'
  when:
    - "'http_proxy' in ansible_env or 'https_proxy' in ansible_env"
- name: Ensure docker service is running
  become: true
  systemd:
    name: docker
    daemon_reload: true
    state: started
- name: Installing docker python library
  become: "{{ not lookup('env','VIRTUAL_ENV') }}"
  pip:
    name: docker
  register: my_result
  until: my_result is succeeded
  retries: 5
  delay: 10
