---
- name: Creating {{ prefix }}/grafana
  become: true
  file:
    path: '{{ prefix }}/grafana'
    state: directory
    mode: '0777'
  when:
    - grafana_deploy
- name: Starting Grafana
  become: true
  docker_container:
    name: grafana
    image: grafana/grafana
    pull: '{{ docker_pull }}'
    recreate: '{{ docker_recreate }}'
    published_ports:
      - '{{ grafana_port }}:3000'
    volumes:
      - '{{ prefix }}/grafana:/var/lib/grafana'
  when:
    - grafana_deploy
- name: Waiting Grafana
  pause:
    seconds: '{{ grafana_wait }}'
  when:
    - docker_recreate
    - grafana_deploy
- name: Adding InfluxDB data source in Grafana
  grafana_datasource:
    name: 'influxdb'
    grafana_url: 'http://{{ ipaddress }}:{{ grafana_port }}'
    ds_type: 'influxdb'
    ds_url: '{{ influxdb_url }}'
    database: '{{ project }}'
  when:
    - grafana_deploy
