---
- name: Creating {{ prefix }}/grafana
  become: true
  file:
    path: '{{ prefix }}/grafana'
    state: directory
    mode: '0777'
  when:
    - grafana_deploy
- name: Starting Grafana
  become: true
  community.general.docker_container:
    name: grafana
    image: grafana/grafana
    pull: '{{ docker_pull }}'
    recreate: '{{ docker_recreate }}'
    restart_policy: '{{ docker_restart_policy }}'
    published_ports:
      - '{{ grafana_port }}:3000'
    volumes:
      - '{{ prefix }}/grafana:/var/lib/grafana'
  notify:
    - Waiting Grafana
  when:
    - grafana_deploy
- name: Flushing handlers
  meta: flush_handlers
- name: Adding InfluxDB data source in Grafana
  community.grafana.grafana_datasource:
    name: 'influxdb'
    grafana_url: 'http://{{ ipaddress }}:{{ grafana_port }}'
    ds_type: 'influxdb'
    ds_url: '{{ influxdb_url }}'
    database: '{{ project }}'
  when:
    - grafana_deploy
