---
- name: Creating {{ prefix }}/grafana
  become: true
  file:
    path: '{{ prefix }}/grafana'
    state: directory
    mode: '0777'
  when:
    - grafana_deploy
    - not use_kubernetes
- name: Starting Grafana
  community.general.docker_container:
    name: grafana
    image: grafana/grafana
    pull: '{{ docker_pull }}'
    recreate: '{{ docker_recreate }}'
    restart_policy: '{{ docker_restart_policy }}'
    published_ports:
      - '{{ grafana_port }}:3000'
    volumes:
      - '{{ prefix }}/grafana:/var/lib/grafana'
  notify:
    - Waiting Grafana
  when:
    - grafana_deploy
    - not use_kubernetes
- name: Adding Grafana chart repository
  community.kubernetes.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts
  when:
    - grafana_deploy
    - use_kubernetes
- name: Installing Grafana helm chart
  community.kubernetes.helm:
    name: grafana
    chart_ref: grafana/grafana
    release_namespace: default
    wait: true
  notify:
    - Waiting Grafana
  when:
    - grafana_deploy
    - use_kubernetes
- name: Creating xtesting@grafana.service
  become: true
  template:
    src: grafana.service.j2
    dest: '/etc/systemd/system/xtesting@grafana.service'
    mode: '0644'
  when:
    - grafana_deploy
    - use_kubernetes
- name: Restarting xtesting@grafana.service
  become: true
  systemd:
    state: restarted
    daemon_reload: true
    name: xtesting@grafana
  when:
    - grafana_deploy
    - use_kubernetes
- name: Flushing handlers
  meta: flush_handlers
- name: Adding InfluxDB data source in Grafana
  community.grafana.grafana_datasource:
    name: 'influxdb'
    grafana_url: 'http://{{ ipaddress }}:{{ grafana_port }}'
    ds_type: 'influxdb'
    ds_url: '{{ influxdb_url }}'
    database: '{{ project }}'
  when:
    - grafana_deploy
