---
- name: Installing jenkins-job-builder
  become: "{{ not lookup('env','VIRTUAL_ENV') }}"
  pip:
    name: jenkins-job-builder
  register: my_result
  until: my_result is succeeded
  retries: 5
  delay: 10
  when:
    - jenkins_deploy or jenkins_configure
- name: Starting Jenkins
  community.general.docker_container:
    name: jenkins
    image: ollivier/xtesting-jenkins
    pull: '{{ docker_pull }}'
    recreate: '{{ docker_recreate }}'
    restart_policy: '{{ docker_restart_policy }}'
    published_ports:
      - '{{ jenkins_port }}:8080'
      - '{{ jenkins_jnlp_port }}:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '{{ prefix }}/jenkins:/var/jenkins_home'
    container_default_behavior: no_defaults
  notify:
    - Waiting Jenkins
  when:
    - jenkins_deploy
    - jenkins_network_mode != 'host'
    - not use_kubernetes
- name: Starting Jenkins
  community.general.docker_container:
    name: jenkins
    image: ollivier/xtesting-jenkins
    pull: '{{ docker_pull }}'
    recreate: '{{ docker_recreate }}'
    restart_policy: '{{ docker_restart_policy }}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '{{ prefix }}/jenkins:/var/jenkins_home'
    network_mode: host
    container_default_behavior: no_defaults
  notify:
    - Waiting Jenkins
  when:
    - jenkins_deploy
    - jenkins_network_mode == 'host'
    - not use_kubernetes
- name: Adding Jenkins chart repository
  community.kubernetes.helm_repository:
    name: jenkins
    repo_url: https://charts.jenkins.io
  when:
    - jenkins_deploy
    - use_kubernetes
- name: Installing Jenkins helm chart
  community.kubernetes.helm:
    name: jenkins
    chart_ref: jenkins/jenkins
    release_namespace: default
    values:
      controller:
        adminUser: '{{ jenkins_user }}'
        adminPassword: '{{ jenkins_password }}'
        jenkinsUrl: '{{ jenkins_url }}'
        overwritePlugins: true
        installPlugins:
          - kubernetes
          - workflow-aggregator
          - git
          - configuration-as-code
          - build-blocker-plugin
          - git-client
          - gerrit-code-review
          - gerrit-trigger
          - gerrit-verify-status-reporter
          - jenkins-multijob-plugin
          - nodelabelparameter
          - random-string-parameter
          - copyartifact
        serviceType: NodePort
        nodePort: '{{ jenkins_port }}'
        agentListenerServiceType: NodePort
        agentListenerPort: '{{ jenkins_jnlp_port }}'
      agent:
        image: "jenkins/jnlp-agent-docker"
        tag: "latest"
        command: "jenkins-agent"
        envVars:
          - name: DOCKER_HOST
            value: tcp://127.0.0.1:2375
        yamlTemplate: |-
          apiVersion: v1
          kind: Pod
          spec:
            containers:
            - env:
              - name: "DOCKER_TLS_CERTDIR"
                value: ""
              image: "docker:19-dind"
              name: "dind"
              securityContext:
                privileged: true
              tty: false
              volumeMounts:
              - mountPath: "/home/jenkins"
                name: "workspace-volume"
                readOnly: false
              - mountPath: "/var/lib/xtesting"
                name: "config"
                readOnly: true
            volumes:
            - name: config
              configMap:
                name: xtesting
      yamlMergeStrategy: "override"
    wait: true
    wait_timeout: 600s
  when:
    - jenkins_deploy
    - use_kubernetes
- name: Flushing handlers
  meta: flush_handlers
- name: Creating jenkins_jobs.ini
  template:
    src: jenkins_jobs.ini.j2
    dest: '{{ tmp_dir }}/jenkins_jobs.ini'
    mode: '0644'
  when:
    - jenkins_configure
- name: Creating {{ project }}.yaml
  template:
    src: run.yaml.j2
    dest: '{{ tmp_dir }}/{{ project }}.yaml'
    mode: '0644'
  when:
    - jenkins_create_jobs
- name: Loading Jenkins jobs
  command: |
    jenkins-jobs --conf \
      {{ tmp_dir }}/jenkins_jobs.ini update {{ tmp_dir }}/{{ project }}.yaml
  register: exit_code
  changed_when: exit_code.rc == 0
  when:
    - jenkins_configure
    - jenkins_create_jobs
