---
- name: Starting Kibana
  become: true
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana-oss:7.7.1
    pull: '{{ docker_pull }}'
    recreate: '{{ docker_recreate }}'
    restart_policy: '{{ docker_restart_policy }}'
    env:
      ELASTICSEARCH_HOSTS: '{{ elasticsearch_url }}'
    published_ports:
      - '{{ kibana_port }}:5601'
  notify:
    - Waiting Kibana
  when:
    - kibana_deploy
