---
- name: Starting Minio
  community.general.docker_container:
    name: minio
    image: minio/minio
    pull: '{{ docker_pull }}'
    recreate: '{{ docker_recreate }}'
    restart_policy: '{{ docker_restart_policy }}'
    command: server /data
    env:
      MINIO_ACCESS_KEY: '{{ aws_access_key_id }}'
      MINIO_SECRET_KEY: '{{ aws_secret_access_key }}'
    published_ports:
      - '{{ minio_port }}:9000'
    volumes:
      - '{{ prefix }}/minio:/data'
  when:
    - minio_deploy
    - not use_kubernetes
- name: Adding Minio chart repository
  community.kubernetes.helm_repository:
    name: minio
    repo_url: https://helm.min.io/
  when:
    - minio_deploy
    - use_kubernetes
- name: Installing Minio helm chart
  community.kubernetes.helm:
    name: minio
    chart_ref: minio/minio
    release_namespace: default
    values:
      accessKey: '{{ aws_access_key_id }}'
      secretKey: '{{ aws_secret_access_key }}'
    wait: true
  when:
    - minio_deploy
    - use_kubernetes
- name: Creating xtesting@minio.service
  become: true
  template:
    src: minio.service.j2
    dest: '/etc/systemd/system/xtesting@minio.service'
    mode: '0644'
  when:
    - minio_deploy
    - use_kubernetes
- name: Restarting xtesting@minio.service
  become: true
  systemd:
    state: restarted
    daemon_reload: true
    name: xtesting@minio
  when:
    - minio_deploy
    - use_kubernetes
- name: Starting S3www
  community.general.docker_container:
    name: s3www
    image: ollivier/xtesting-s3www
    pull: '{{ docker_pull }}'
    recreate: '{{ docker_recreate }}'
    restart_policy: '{{ docker_restart_policy }}'
    published_ports:
      - '{{ s3www_port }}:8080'
    env:
      ENDPOINT: 'http://{{ ipaddress }}:{{ minio_port }}'
      ACCESSKEY: '{{ aws_access_key_id }}'
      SECRETKEY: '{{ aws_secret_access_key }}'
      BUCKET: '{{ bucket }}'
  when:
    - minio_deploy
- name: Setting s3 endpoint url if Minio
  set_fact:
    s3_endpoint_url: 'http://{{ ipaddress }}:{{ minio_port }}'
  when:
    - publish_to_s3
    - minio_deploy
- name: Setting http dst url if Minio
  set_fact:
    http_dst_url: 'http://{{ external_ipaddress }}:{{ s3www_port }}'
  when:
    - publish_to_s3
    - minio_deploy
