---
- name: Starting PostgreSQL
  become: true
  community.general.docker_container:
    name: postgres
    image: postgres:alpine
    pull: '{{ docker_pull }}'
    recreate: '{{ docker_recreate }}'
    restart_policy: '{{ docker_restart_policy }}'
    published_ports:
      - '{{ postgres_port }}:5432'
    volumes:
      - '{{ prefix }}/postgres:/var/lib/postgresql/data'
    env:
      POSTGRES_USER: '{{ postgres_username }}'
      POSTGRES_PASSWORD: '{{ postgres_password }}'
      POSTGRES_DB: '{{ postgres_database }}'
  notify:
    - Waiting PostgreSQL
  when:
    - postgres_deploy
    - not use_kubernetes
- name: Adding PostgreSQL chart repository
  community.kubernetes.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami
  when:
    - postgres_deploy
    - use_kubernetes
- name: Installing PostgreSQL helm chart
  community.kubernetes.helm:
    name: postgres
    chart_ref: bitnami/postgresql
    release_namespace: default
    values:
      postgresqlUsername: '{{ postgres_username }}'
      postgresqlPassword: '{{ postgres_password }}'
      postgresqlDatabase: '{{ postgres_database }}'
    wait: true
  when:
    - postgres_deploy
    - use_kubernetes
- name: Creating xtesting@postgres.service
  become: true
  template:
    src: postgres.service.j2
    dest: '/etc/systemd/system/xtesting@postgres.service'
    mode: '0644'
  when:
    - postgres_deploy
    - use_kubernetes
- name: Restarting xtesting@postgres.service
  become: true
  systemd:
    state: restarted
    daemon_reload: true
    name: xtesting@postgres
  when:
    - postgres_deploy
    - use_kubernetes
