---
- name: Installing python-dnf
  become: true
  shell: yum install python-dnf -y
  when:
    - ansible_python.version.major==2
- name: Installing python3-dnf
  become: true
  shell: yum install python3-dnf -y
  when:
    - ansible_python.version.major==3
- name: Installing python-pip
  become: true
  yum:
    name:
      - python-pip
    update_cache: true
  when:
    - ansible_python.version.major==2
- name: Installing python3-pip
  become: true
  yum:
    name:
      - python3-pip
    update_cache: true
  when:
    - ansible_python.version.major==3
- name: Adding Docker CE repository
  become: true
  changed_when: true
  shell: |
    yum-config-manager \
      --add-repo https://download.docker.com/linux/centos/docker-ce.repo
- name: Installing docker-ce
  become: true
  yum:
    name:
      - docker-ce
    update_cache: true
- name: Populating service ansible_facts
  service_facts:
- name: Disabling firewalld
  become: true
  systemd:
    name: firewalld
    state: stopped
  when: ansible_facts.services['firewalld'] is defined
- name: Changing state of selinux
  become: true
  ansible.posix.selinux:
    policy: targeted
    state: permissive
- name: Upgrading six
  become: "{{ not lookup('env','VIRTUAL_ENV') }}"
  pip:
    name: six>=1.10.0
  register: my_result
  until: my_result is succeeded
  retries: 5
  delay: 10
  when:
    - jenkins_deploy or jenkins_configure
    - ansible_distribution_major_version == '7'
