---
- name: Starting Docker Registry
  community.general.docker_container:
    name: registry
    image: registry:2
    pull: '{{ docker_pull }}'
    recreate: '{{ docker_recreate }}'
    restart_policy: '{{ docker_restart_policy }}'
    published_ports:
      - '{{ registry_port }}:5000'
    volumes:
      - '{{ prefix }}/registry:/var/lib/registry'
    container_default_behavior: no_defaults
  when:
    - registry_deploy
