---
- name: Waiting Jenkins
  uri:
    url: "{{ jenkins_url }}"
    method: GET
  register: _result
  until: _result.status == 200
  retries: "{{ ((jenkins_wait |int) / 5) |int }}"
  delay: 5
- name: Waiting Cachet
  pause:
    seconds: '{{ cachet_wait }}'
- name: Waiting MongoDB
  pause:
    seconds: '{{ mongo_wait }}'
- name: Waiting Kibana
  pause:
    seconds: '{{ kibana_wait }}'
- name: Waiting Grafana
  pause:
    seconds: '{{ grafana_wait }}'
- name: Waiting Fluentd
  pause:
    seconds: "{{ fluentd_wait }}"
- name: Waiting PostgreSQL
  pause:
    seconds: '{{ postgres_wait }}'
- name: Waiting Elasticsearch
  pause:
    seconds: '{{ elasticsearch_wait }}'
- name: Waiting GitLab
  uri:
    url: "{{ gitlab_url }}"
    method: GET
  register: _result
  until: _result.status == 200
  retries: "{{ ((gitlab_wait |int) / 5) |int }}"
  delay: 5
- name: Waiting TestAPI
  pause:
    seconds: '{{ testapi_wait }}'
- name: Waiting Gitea
  uri:
    url: "{{ gitea_url }}"
    method: GET
  register: _result
  until: _result.status == 200
  retries: "{{ ((gitea_wait |int) / 5) |int }}"
  delay: 5
